# Sample input that can be used in the Cage playground
[cage.playground]
name = "Claude Shannon"

# Read more about how to use the cage.toml in our docs: https://docs.evervault.com/reference/cagetoml
